/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author chris
 */
        
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.Edge;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.BorderLayout;

import Clases.Neurona;
import Clases.ConexionSinaptica;

public class VentanaPrincipal extends javax.swing.JFrame {

    // Instancia global de la red neuronal para toda la ventana
    private Clases.redNeuronal miRed = new Clases.redNeuronal();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

  public VentanaPrincipal() {
        initComponents();
        
        // Activar el motor visual de GraphStream en modo Swing
        System.setProperty("org.graphstream.ui", "swing");
        
        // Centrar la aplicacion en la pantalla al abrirse
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PanelControl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbOrigen = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbDestino = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEstado = new javax.swing.JTextArea();
        PanelVisorGrafo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar Neuronas (CSV)");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Cargar Neurotransmisores");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(36, 36, 36))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setText("Neurona Origen");

        cmbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Neurona Destino");

        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("Analisar zonas (BFS/DFS)");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Calcular Ruta (Dijkstra)");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Limpiar Pantalla");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        txtEstado.setColumns(20);
        txtEstado.setRows(5);
        jScrollPane1.setViewportView(txtEstado);

        javax.swing.GroupLayout PanelControlLayout = new javax.swing.GroupLayout(PanelControl);
        PanelControl.setLayout(PanelControlLayout);
        PanelControlLayout.setHorizontalGroup(
            PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlLayout.createSequentialGroup()
                .addGroup(PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelControlLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton5))
                    .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        PanelControlLayout.setVerticalGroup(
            PanelControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        PanelVisorGrafo.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelVisorGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(285, 285, 285))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(PanelVisorGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
            javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
            int opc = selector.showOpenDialog(this);
            
            if (opc == javax.swing.JFileChooser.APPROVE_OPTION) {
                String ruta = selector.getSelectedFile().getAbsolutePath();
                
                Clases.CargadorArchivo cargador = new Clases.CargadorArchivo();
                
                // CORRECCIÓN: Quitamos ", ruta" para dejar solo los 2 parámetros que pide tu clase
                cargador.cargarRedNeuronal(miRed, miRed.getDiccionario());
                
                actualizarCombos(); 
                dibujarRed(null, null); 
                
                txtEstado.setText("Red cargada con exito.");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   if (cmbOrigen.getSelectedItem() == null || cmbDestino.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione los dos puntos.");
            return;
        }

        String orig = cmbOrigen.getSelectedItem().toString();
        String dest = cmbDestino.getSelectedItem().toString();

        Clases.CalculadorRutaOptima dijkstra = new Clases.CalculadorRutaOptima();
        Edd.ListaEnlazada<Neurona> caminoVerde = dijkstra.calcularRuta(miRed, orig, dest);

        if (caminoVerde == null || caminoVerde.estaVacia()) {
            txtEstado.setText("No existe una ruta entre " + orig + " y " + dest);
            dibujarRed(null, null); 
        } else {
            dibujarRed(null, caminoVerde); // Manda el camino para pintarlo de verde
            txtEstado.setText("Ruta mas corta encontrada.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  dibujarRed(null, null);
        txtEstado.setText("Grafo restaurado al estado original.");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if (cmbOrigen.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cargue el archivo primero.");
            return;
        }

        String inicioId = cmbOrigen.getSelectedItem().toString();
        Clases.AnalizadorConectividad analizador = new Clases.AnalizadorConectividad();
        Edd.ListaEnlazada<Neurona> aisladas = analizador.obtenerZonasAisladas(miRed, inicioId);

        dibujarRed(aisladas, null); // Manda las aisladas para pintarlas de rojo

        if (aisladas.estaVacia()) {
            txtEstado.setText("Resultado: Red totalmente conectada.");
        } else {
            txtEstado.setText("Alerta: Hay " + aisladas.getTamaño() + " nodos aislados desde " + inicioId);
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelControl;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelVisorGrafo;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtEstado;
    // End of variables declaration//GEN-END:variables

// Metodo para llenar los combobox con los IDs
    private void actualizarCombos() {
        cmbOrigen.removeAllItems();
        cmbDestino.removeAllItems();
        
        Edd.Nodo<Neurona> aux = miRed.getListaTodasLasNeuronas().getCabeza();
        while (aux != null) {
            cmbOrigen.addItem(aux.getDato().getId());
            cmbDestino.addItem(aux.getDato().getId());
            aux = aux.getSiguiente();
        }
    }

    // Metodo para pintar el grafo en la pantalla de NetBeans
    public void dibujarRed(Edd.ListaEnlazada<Neurona> rojas, Edd.ListaEnlazada<Neurona> verdes) {
        Graph grafo = new SingleGraph("Red");
        
        // Estilos basicos (Estilo de estudiante)
        grafo.setAttribute("ui.stylesheet", 
            "node { fill-color: blue; size: 25px; text-color: white; } " +
            "node.aislada { fill-color: red; size: 30px; } " + 
            "node.ruta { fill-color: green; size: 30px; } " +    
            "edge { fill-color: black; } " +
            "edge.ruta { fill-color: green; size: 3px; }");      

        // 1. Agregar todos los nodos del grafo
        Edd.Nodo<Neurona> aux = miRed.getListaTodasLasNeuronas().getCabeza();
        while (aux != null) {
            String id = aux.getDato().getId();
            Node nodoNuevo = grafo.addNode(id);
            nodoNuevo.setAttribute("ui.label", id);
            
            // Si el analisis dice que es aislada va roja, si es de ruta va verde
            if (rojas != null && rojas.contiene(aux.getDato())) {
                nodoNuevo.setAttribute("ui.class", "aislada");
            } else if (verdes != null && verdes.contiene(aux.getDato())) {
                nodoNuevo.setAttribute("ui.class", "ruta");
            }
            aux = aux.getSiguiente();
        }

        // 2. Agregar todas las aristas (conexiones)
        Edd.Nodo<ConexionSinaptica> auxConex = miRed.getTodasLasConexiones().getCabeza();
        while (auxConex != null) {
            ConexionSinaptica c = auxConex.getDato();
            String idOri = c.getOrigen().getId();
            String idDes = c.getDestino().getId();
            
            try {
                Edge arista = grafo.addEdge(idOri + "-" + idDes, idOri, idDes, true);
                arista.setAttribute("ui.label", c.getDistancia());
                
                // Pintar la linea de verde si pertenece a la ruta optima
                if (verdes != null && verdes.contiene(c.getOrigen()) && verdes.contiene(c.getDestino())) {
                    arista.setAttribute("ui.class", "ruta");
                }
            } catch(Exception e) {} 
            
            auxConex = auxConex.getSiguiente();
        }

        // 3. Montar el visor de GraphStream dentro de tu panel de NetBeans (Con P mayuscula)
        Viewer visor = new SwingViewer(grafo, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        visor.enableAutoLayout(); 
        ViewPanel panelGraph = (ViewPanel) visor.addDefaultView(false);
        
        PanelVisorGrafo.removeAll();
        PanelVisorGrafo.add(panelGraph, BorderLayout.CENTER);
        PanelVisorGrafo.revalidate();
        PanelVisorGrafo.repaint();
    }
    }




